version: '{build}'
shallow_clone: true
clone_depth: 1
init:
- git config --global core.autocrlf input

environment:
  matrix:
    - RUBY_VERSION: 22
    - RUBY_VERSION: 21
    - RUBY_VERSION: 200
    - RUBY_VERSION: 193

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%

before_build:
  - set PATH=%RUBY%;%PATH%

build:

build_script:
  - rake gem
